name: Push

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run test

  release:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          runCmd: |
            npm ci
            npx semantic-release
