name: Push

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  release:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
