name: Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run ci:lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run ci:build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run ci:test

  release:
    needs: [lint, build, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev Container Build and Run
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            npm ci
            npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: "1"
